- name: topics
  connection: local
  hosts: localhost
  vars:
    ansible_python_interpreter: /home/kochjo/IPA/env2/bin/python
  tasks:
    - name: single topic foobar
      kafka_topic:
        name: alot
        state: present
        partitions: 2
        replication_factor: 2
        bootstrap_server:
         - localhost:9092
        cleanup_policy: delete
        compression_type: gzip
        delete_retention_ms: 1h
        file_delete_delay_ms: 1h
        flush_messages: 50
        flush_ms: 3s
        index_interval_bytes: 100kB
        max_message_bytes: 150MiB
        message_format_version: 2.1-IV0
        message_timestamp_difference_max_ms: 3m
        message_timestamp_type: LogAppendTime
        min_cleanable_dirty_ratio: 0.6
        min_compaction_lag_ms: 10s
        min_insync_replicas: 1
        preallocate: true
        retention_bytes: 200KiB
        retention_ms: 1ms
        segment_bytes: 2GiB
        segment_index_bytes: 3MB
        segment_jitter_ms: 3d
        segment_ms: 1d
        unclean_leader_election_enable: true
        message_downconversion_enable: false
