- name: topics
  connection: local
  hosts: localhost
  vars:
    ansible_python_interpreter: /home/kochjo/IPA/env2/bin/python
  tasks:
    - name: single topic foobar
      kafka_topic:
        name: alot
        state: present
        partitions: 2
        replication_factor: 2
        bootstrap_server:
         - "[::1]:9092"
        cleanup_policy: delete
        compression_type: gzip
        delete_retention_ms: 10ms
        file_delete_delay_ms: 10ms
        flush_messages: 50
        flush_ms: 10ms
        index_interval_bytes: 100kB
        max_message_bytes: 1MiB
        message_format_version: 2.1-IV0
        message_timestamp_difference_max_ms: 10ms
        message_timestamp_type: LogAppendTime
        min_cleanable_dirty_ratio: 0.6
        min_compaction_lag_ms: 10ms
        min_insync_replicas: 1
        preallocate: true
        retention_bytes: 1000B
        retention_ms: 10ms
        segment_bytes: 14B
        segment_index_bytes: 4KiB
        segment_jitter_ms: 10ms
        segment_ms: 10ms
        unclean_leader_election_enable: true
        message_downconversion_enable: false
