- name: testing
  connection: local
  hosts: localhost
  vars:
    ansible_python_interpreter: /home/kochjo/IPA/.venv/bin/python3
  tasks:
    - name: create topic "foo"
      kafka_topic:
        name: foo
