- name: testing
  connection: local
  hosts: localhost
  vars:
    ansible_python_interpreter: /home/kochjo/IPA/.venv/bin/python3
  tasks:
    - name: test the module
      kafka_topic:
        name: "bar.two"
        state: present
        partitions: 3
        replication_factor: 2
        bootstrap_server:
          - 127.0.0.1:9092
